name: upsen_entrance
description: "A new Upsen Apps for Entrance with tablet"
publish_to: "none"
# version: 0.1.0 before 1
version: 1.1.1+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  get: ^4.7.2
  image: ^4.5.4
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  camera: ^0.11.2
  permission_handler: ^12.0.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1
  geolocator: ^14.0.2
  intl: ^0.20.2

  #untuk android 15
  edge_to_edge: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/models/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  color: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/icon.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
