name: upget
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  get: ^4.7.2
  image: ^4.5.4
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  camera: ^0.11.2
  permission_handler: ^12.0.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/models/
